---
booktitle: Proceedings of The First AAAI Bridge Program on AI for Medicine and Healthcare
shortname: AIMedHealth
year: '2025'
volume: '281'
start: &1 2025-02-25
end: 2025-02-25
published: 2025-04-22
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AIMedHealth-2025
month: 0
cycles: false
bibtex_editor: Wu, Junde and Zhu, Jiayuan and Xu, Min and Jin, Yueming
editor:
- given: Junde
  family: Wu
- given: Jiayuan
  family: Zhu
- given: Min
  family: Xu
- given: Yueming
  family: Jin
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The First AAAI Bridge Program on AI for Medicine and Healthcare
    Held in Pennsylvania Convention Center, Philadelphia, Pennsylvania, USA on 25 February 2025

  Published as Volume 281 by the Proceedings of Machine Learning Research on 22 April 2025.

  Volume Edited by:
    Junde Wu
    Jiayuan Zhu
    Min Xu
    Yueming Jin

  Series Editors:
    Neil D. Lawrence
date_str: 25 Feb
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v281"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v281
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v281
email: ''
conference:
  name: AAAI Bridge Program on AI for Medicine and Healthcare
  url: https://sites.google.com/view/aimedhealth-aaai/home
  location: Pennsylvania Convention Center, Philadelphia, Pennsylvania, USA
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: "/Users/neil/mlresearch/v281/aaaimedhealth25.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v281/aaaimedhealth25.bib
